apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: myweb-rss
spec:
      replicas: 3
      selector:
          matchExpressions:
              - { key: env, operator: In,values: [ production ] }
              - { key: region, operator: In, values: [ IN ] }
      template:
         metadata:
            name: myweb-prod
            labels:
              env: production
              dc: "2"
              region: IN
         spec:
            containers:
             - name: myweb-con
               image: httpd
